# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Find_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 525)
        self.SaveFileButton = QtWidgets.QPushButton(Dialog)
        self.SaveFileButton.setGeometry(QtCore.QRect(280, 470, 93, 28))
        self.SaveFileButton.setObjectName("SaveFileButton")
        self.BackButton = QtWidgets.QPushButton(Dialog)
        self.BackButton.setGeometry(QtCore.QRect(380, 470, 93, 28))
        self.BackButton.setObjectName("BackButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 10, 801, 441))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SaveFileButton.setText(_translate("Dialog", "Save"))
        self.BackButton.setText(_translate("Dialog", "Back"))
    def save_file(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getSaveFileName(self, "Save File", "", "Text Files (*.txt);;All Files (*)", options=options)
        text = self.textEdit.toPlainText()
        if file_name:
            with open(file_name, "w") as file:
                file.write(text)
    def close_window(self):
        self.close()            

class MyDialog(QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.SaveFileButton.clicked.connect(self.save_file)
        self.BackButton.clicked.connect(self.close_window)