# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Change_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QFileDialog, QDialog, QVBoxLayout, QTableWidgetItem
import Choose_Ui, Warning_Ui


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 396)
        self.Back_button = QtWidgets.QPushButton(Dialog)
        self.Back_button.setGeometry(QtCore.QRect(20, 330, 93, 28))
        self.Back_button.setObjectName("Back_button")
        self.ChangeButton = QtWidgets.QPushButton(Dialog)
        self.ChangeButton.setGeometry(QtCore.QRect(290, 330, 93, 28))
        self.ChangeButton.setObjectName("ChangeButton")
        self.Name_label = QtWidgets.QLabel(Dialog)
        self.Name_label.setGeometry(QtCore.QRect(80, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Name_label.setFont(font)
        self.Name_label.setTextFormat(QtCore.Qt.AutoText)
        self.Name_label.setObjectName("Name_label")
        self.Name_line = QtWidgets.QLineEdit(Dialog)
        self.Name_line.setGeometry(QtCore.QRect(160, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Name_line.setFont(font)
        self.Name_line.setObjectName("Name_line")
        self.Weigth_line = QtWidgets.QLineEdit(Dialog)
        self.Weigth_line.setGeometry(QtCore.QRect(160, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Weigth_line.setFont(font)
        self.Weigth_line.setObjectName("Weigth_line")
        self.weight_label = QtWidgets.QLabel(Dialog)
        self.weight_label.setGeometry(QtCore.QRect(80, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weight_label.setFont(font)
        self.weight_label.setTextFormat(QtCore.Qt.AutoText)
        self.weight_label.setObjectName("weight_label")
        self.Cost_line = QtWidgets.QLineEdit(Dialog)
        self.Cost_line.setGeometry(QtCore.QRect(160, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Cost_line.setFont(font)
        self.Cost_line.setObjectName("Cost_line")
        self.Cost_label = QtWidgets.QLabel(Dialog)
        self.Cost_label.setGeometry(QtCore.QRect(80, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Cost_label.setFont(font)
        self.Cost_label.setTextFormat(QtCore.Qt.AutoText)
        self.Cost_label.setObjectName("Cost_label")
        self.ErrorLable = QtWidgets.QLabel(Dialog)
        self.ErrorLable.setGeometry(QtCore.QRect(110, 270, 201, 20))
        self.ErrorLable.setText("")
        self.ErrorLable.setObjectName("ErrorLable")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Back_button.setText(_translate("Dialog", "Back"))
        self.ChangeButton.setText(_translate("Dialog", "Change"))
        self.Name_label.setText(_translate("Dialog", "Name:"))
        self.weight_label.setText(_translate("Dialog", "Weight:"))
        self.Cost_label.setText(_translate("Dialog", "Cost:"))

    def close_window(self):
        self.choose = Choose_Ui.MyDialog()
        # Получаем текст из строковых полей
        self.text1 = self.Name_line.text()
        self.text2 = self.Weigth_line.text()
        self.text3 = self.Cost_line.text()

        # Если хотя бы одно поле не пустое, показываем предупреждение
        if self.text1 or self.text2 or self.text3:
            self.warning = Warning_Ui.MyDialog()
            self.warning.show()
            self.warning.Yes_button.clicked.connect(self.closing)
        else:
            self.choose.open()
            self.close()
    def closing(self):
        self.table.open()
        self.close()
        
    

class MyDialog(QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.Back_button.clicked.connect(self.close_window)