# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QDialog
import Add_item_Ui


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 175)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 50, 191, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 90, 201, 16))
        self.label_3.setObjectName("label_3")
        self.Yes_button = QtWidgets.QPushButton(Dialog)
        self.Yes_button.setGeometry(QtCore.QRect(100, 120, 93, 28))
        self.Yes_button.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Yes_button.setObjectName("Yes_button")
        self.No_button_2 = QtWidgets.QPushButton(Dialog)
        self.No_button_2.setGeometry(QtCore.QRect(210, 120, 93, 28))
        self.No_button_2.setObjectName("No_button_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Warning</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "The entered data is not saved."))
        self.label_3.setText(_translate("Dialog", " Do you want to close the window?"))
        self.Yes_button.setText(_translate("Dialog", "Yes"))
        self.No_button_2.setText(_translate("Dialog", "No"))
    def close_window(self):
        self.close()
    def close_two_winds(self):
        self.close()

class MyDialog(QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.Yes_button.clicked.connect(self.close_two_winds)
        self.No_button_2.clicked.connect(self.close_window)
